### ISSUE TITLE
[FR] Can you provide a release based on the scratch/igc branch?

### ISSUE THREAD

**Issue by nanakura** [kiennq/emacs-build#6]
Combining mps with igc can achieve better performance. Providing releases from the igc branch allows more people to use the igc branch so that maintainers can receive feedback.

**Comment by pipcet** [comment]
I think the `-mps` release is what you want. It's based on the `scratch/igc` branch, and includes some fixes necessary for Windows builds.

**Comment by nanakura** [comment]
> I think the `-mps` release is what you want. It's based on the `scratch/igc` branch, and includes some fixes necessary for Windows builds.

no, -mps release is based on HEAD(https://github.com/kiennq/emacs.git)
![image](https://github.com/user-attachments/assets/c5920a1c-bb57-4e5d-9da0-776285d01267)

**Comment by nanakura** [comment]
> I think the `-mps` release is what you want. It's based on the `scratch/igc` branch, and includes some fixes necessary for Windows builds.

oh, you mean https://github.com/kiennq/emacs.git is a fork of igc branch?

**Comment by nanakura** [comment]
> I think the `-mps` release is what you want. It's based on the `scratch/igc` branch, and includes some fixes necessary for Windows builds.

Thanks for your help
